[phases.setup]
aptPkgs = ["...", "ffmpeg"]

[variables]
FFMPEG_PATH = "/usr/bin/ffmpeg"  # Changed from /opt/homebrew/bin/ffmpeg
FFPROBE_PATH = "/usr/bin/ffprobe"  # Changed from /opt/homebrew/bin/ffprobe


[phases.build]
cmds = [
  "which ffmpeg || echo 'FFmpeg not found'",
  "ffmpeg -version || echo 'Cannot run FFmpeg'",
  "ls -la /usr/bin/ffmpeg || echo 'No FFmpeg at /usr/bin'",
  "echo $PATH"
]